// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CostaFascinosa.Data;

public partial class ReservasActividade
{
    public int IdReservaAct { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdActividad { get; set; }

    public int? IdConsumo { get; set; }

    public DateTime? Fecha { get; set; }

    public int? CantidadReservada { get; set; }

    public decimal? CostoUnitario { get; set; }

    public virtual Actividade IdActividadNavigation { get; set; }

    public virtual ConsumosHabitacione IdConsumoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}