// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_CostaFascinosa.Data;

public partial class ConsumosGastronomico
{
    public int IdConsumoGastronomico { get; set; }

    public int? IdConsumo { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdProducto { get; set; }

    public int? Cantidad { get; set; }

    public decimal? Precio { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual ConsumosHabitacione IdConsumoNavigation { get; set; }

    public virtual ProductosGastronomico IdProductoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}