// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_CostaFascinosa.Data;

public partial class TiposDocumento
{
    public int IdTipoDoc { get; set; }

    public string Tipo { get; set; }

    public virtual ICollection<Pasajero> Pasajeros { get; set; } = new List<Pasajero>();
}