// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_CostaFascinosa.Data;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string Nombre { get; set; }

    public int? Contraseña { get; set; }

    public int? IdPasajero { get; set; }

    public virtual ICollection<ConsumosGastronomico> ConsumosGastronomicos { get; set; } = new List<ConsumosGastronomico>();

    public virtual Pasajero IdPasajeroNavigation { get; set; }

    public virtual ICollection<ResenasActividade> ResenasActividades { get; set; } = new List<ResenasActividade>();

    public virtual ICollection<ResenasAmenity> ResenasAmenities { get; set; } = new List<ResenasAmenity>();

    public virtual ICollection<ResenasServicio> ResenasServicios { get; set; } = new List<ResenasServicio>();

    public virtual ICollection<ReservasActividade> ReservasActividades { get; set; } = new List<ReservasActividade>();

    public virtual ICollection<ReservasServicio> ReservasServicios { get; set; } = new List<ReservasServicio>();
}